version: "3"
volumes:
  db-store:
  db-test-store:
services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/app/Dockerfile
    ports:
      - target: 8080
        published: ${APP_PORT:-8080}
        protocol: tcp
        mode: host
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-smacare}
      - DB_USERNAME=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASS:-secret}
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./build/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-smacare}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  db-test:
    build:
      context: .
      dockerfile: ./build/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${TESTDB_PORT:-3307}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-test-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-smacare_ut}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

